name: Builds on Linux, MacOS and Windows

on:
  push:
    branches:
      - build
  pull_request:
    branches:
      - build

jobs:
    build-macos:
        runs-on: macos-latest
        steps: 
    build-ubuntu:
        runs-on: ubuntu-latest
        steps: 
    build-windows:
        runs-on: windows-latest
        steps: 