name: Tests on Linux, MacOS and Windows

on: [push, pull_request]

jobs:
    build-macos:
        runs-on: macos-latest
        steps:
          - name: checkout
            uses: actions/checkout@v3
          
          - name: Setup node
            uses: actions/setup-node@v3
            with:
              node-version: 16.15.x
              cache: npm
          - name: Install
            run: npm ci

          - name: Testing
            run: npm test
          
    build-ubuntu:
        runs-on: ubuntu-latest
        steps: 
          - name: checkout
            uses: actions/checkout@v3
          
          - name: Setup node
            uses: actions/setup-node@v3
            with:
              node-version: 16.15.x
              cache: npm
          - name: Install
            run: npm ci
            
          - name: Testing
            run: npm test
          
    build-windows:
        runs-on: windows-latest
        steps:
          - name: checkout
            uses: actions/checkout@v3
          
          - name: Setup node
            uses: actions/setup-node@v3
            with:
              node-version: 16.15.x
              cache: npm
          - name: Install
            run: npm ci
          
          - name: Testing
            run: npm test
